=== JaimeMGR/Proyectos/DAM/1º DAM/Lenguaje de marcas/XML/bdproductos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bdproductos" type="bdproductosType"/>
  <xs:complexType name="productoType">
    <xs:sequence>
      <xs:element name="nombre">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="teclado"/>
            <xs:enumeration value="monitor"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="codigo">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="C001"/>
            <xs:enumeration value="C002"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="categoria">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="iva"/>
      <xs:element name="precio">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="15"/>
            <xs:enumeration value="147.2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="descuento">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="10"/>
            <xs:enumeration value="9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="bdproductosType">
    <xs:sequence>
      <xs:element type="productoType" name="producto" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== JaimeMGR/Proyectos/1º DAM/Lenguaje de marcas/XML/bdproductos.xml
<?xml version="1.1" encoding="UTF-8"?>
<bdproductos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bdproductos.xsd">
    <producto>
        <nombre>teclado</nombre>
        <codigo>C001</codigo>
        <categoria>A</categoria>
        <iva>21</iva>
        <precio>15</precio>
        <descuento>10</descuento>
    </producto>
    <producto>
        <nombre>monitor</nombre>
        <codigo>C002</codigo>
        <categoria>B</categoria>
        <iva>21</iva>
        <precio>147.2</precio>
        <descuento>9</descuento>
    </producto>
</bdproductos>
