=== JaimeMGR/Proyectos/DAM/1º DAM/Lenguaje de marcas/XML/centro2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Empresa" type="EmpresaType"/>

<xs:complexType name="nifType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="nacionalidad" type="xs:string" use="optional"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>

<xs:complexType name="personalType">
<xs:sequence>
<xs:element name="nombre" type="xs:string"/>
<xs:element name="apellidos" type="xs:string"/>
<xs:element name="nif" type="nifType"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="laboralType">
<xs:sequence>
<xs:element name="sueldo" type="xs:short"/>
<xs:element name="irpf" type="xs:byte"/>
</xs:sequence>
<xs:attribute name="dep" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="EmpleadoType">
<xs:sequence>
<xs:element name="personal" type="personalType"/>
<xs:element name="laboral" type="laboralType"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="EmpresaType">
<xs:sequence>
<xs:element name="Empleado" type="EmpleadoType" maxOccurs="unbounded" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

</xs:schema>

=== JaimeMGR/Proyectos/DAM/1º DAM/Lenguaje de marcas/XML/conversionxsl/conversionXSL/Empresa.xml
<?xml version="1.1" encoding="UTF-8"?>
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="centro2.xsd">
    <Empleado>
        <personal>
            <nombre>Felipe</nombre>
            <apellidos>Pascual</apellidos>
            <nif nacionalidad="española">1234X</nif>
        </personal>
        <laboral dep="ADM">
            <sueldo>1200</sueldo>
            <irpf>5</irpf>
        </laboral>
    </Empleado>
    <Empleado>
        <personal>
            <nombre>Ana</nombre>
            <apellidos>López</apellidos>
            <nif nacionalidad="italiana">8888</nif>
        </personal>
        <laboral dep="IT">
            <sueldo>1500</sueldo>
            <irpf>4</irpf>
        </laboral>
    </Empleado>
    <Empleado>
        <personal>
            <nombre>Carmen</nombre>
            <apellidos>Ruiz</apellidos>
            <nif nacionalidad="española">3456G</nif>
        </personal>
        <laboral dep="IT">
            <sueldo>1400</sueldo>
            <irpf>2</irpf>
        </laboral>
    </Empleado>
</Empresa>

=== JaimeMGR/Proyectos/DAW/1º DAW/Lenguaje de marcas/XML/empresa.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Empresa [
        <!ELEMENT Empresa (Empleado)*>
        <!ATTLIST Empresa
                xmlns:xsi CDATA #REQUIRED
                xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
        <!ELEMENT Empleado (personal|laboral)*>
        <!ELEMENT personal (nombre|apellidos|nif)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT nif (#PCDATA)>
        <!ATTLIST nif
                nacionalidad CDATA #REQUIRED>
        <!ELEMENT laboral (sueldo|irpf)*>
        <!ATTLIST laboral
                dep CDATA #REQUIRED>
        <!ELEMENT sueldo (#PCDATA)>
        <!ELEMENT irpf (#PCDATA)>
        ]>
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="centro2.xsd">
    <Empleado>
        <personal>
            <nombre>Felipe</nombre>
            <apellidos>Pascual</apellidos>
            <nif nacionalidad="española">1234X</nif>
        </personal>
        <laboral dep="ADM">
            <sueldo>1200</sueldo>
            <irpf>5</irpf>
        </laboral>
    </Empleado>
    <Empleado>
        <personal>
            <nombre>Ana</nombre>
            <apellidos>López</apellidos>
            <nif nacionalidad="italiana">8888</nif>
        </personal>
        <laboral dep="IT">
            <sueldo>1500</sueldo>
            <irpf>4</irpf>
        </laboral>
    </Empleado>
    <Empleado>
        <personal>
            <nombre>Carmen</nombre>
            <apellidos>Ruiz</apellidos>
            <nif nacionalidad="española">3456G</nif>
        </personal>
        <laboral dep="IT">
            <sueldo>1400</sueldo>
            <irpf>2</irpf>
        </laboral>
    </Empleado>
</Empresa>
